# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1e1a07045789204f6e0e28e8719813823c3c17a063a0b0b98ee933a4a3774f8ac1fe0674daef347f2c50a57e9452fb303e161aa0a07f74e4defa9a3a069966d1

test:
  secret_key_base: 96a7d65c0d3a8b6dd06991eb0577eefec8ac8c190a2448c641f3b670fea101242ecea22b1d95426d938de2cd04dc082b22795270c4b8df2bc40c0a3f8b71239c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
